### PR TITLE
fixed disambiguity

### PR DESCRIPTION
**Pull request by esavier**
lua couldn't load library due to 'function disambiguation'. apperently one semicolo to fix them all

### CODE REVIEW

**Comment by starwing** [comment]
I have made a change, could you try it out for work? Thanks for reporting it.

**Comment by esavier** [comment]
i had some more problems with decoder, i will try again fresh , maybe i did something wrong, but of course i will try to provide more help and feedback. 
I belive This issue is solved,

**Comment by starwing** [comment]
@esavier Thank you very much for that! :smile: 

I'm trying to write some logic in C, and new version will give a usefull C interface. but now it slower than [cloudwu's pbc](https://github.com/cloudwu/pbc) about 4 times. I will try to improve it and keep it simple. Hopes this small project can help you :)

(p.s. I'll also try to make a pure lua version of protobuf encode/decode)

**Comment by esavier** [comment]
Its me who should thank you for writting this. If i can help you with finish this project i am sure i will.
BTW, don't mention that your code is slower than C, its LUA problem. Probably if you will compile it with LUAJIT it will be significantly faster since no interpretation will be needed during  runtime. Of course it still will be lagging behind C/C++ but i have chosen your project exactly because its output can be included in any lua file. What i am afraid that your way of generating proto.lua can lead to some variable problems with bigger proto files, specifically LUA's 200 Local Variable limit, But for now lets make it working :+1: 

edit:
There is also an option to generate C shared library with LUA interface, but its tricky one.

**Pull request closed without merging**
